# Experiment
experiment:
  description: test score_one_all method on anime triplet_12 with target loss and nce loss
  author: jiabin
  method: score_one_all
  seed: 42

# Model
model:
  pretrained_path: /mnt/ws-jfs/models/Qwen/Qwen-Image-Edit-2511
  clip_path: /mnt/ws-jfs/models/CLIP/DanbooruCLIP
  insightface_root: /mnt/ws-jfs/models/InsightFace
  insightface_detector_path: /mnt/ws-jfs/models/InsightFace/models/scrfd_10g_bnkps.onnx
  insightface_recognition_path: /mnt/ws-jfs/models/InsightFace/models/glintr100.pth

# Inference
inference:
  image_path: /path/to/input.jpg
  expression: happy
  scales: [0.25, 0.5, 0.75, 1.0]
  output_dir: /path/to/output
  lora_path: null
  method: null
  seed: null
  inf_steps: 50

# Logging
logging:
  checkpointing_steps: 1000
  report_to: tensorboard  # or wandb
  tracker_project_name: qwen-expression

# Dataset
dataset:
  path: /mnt/ws-jfs/data/AnimationCharacters/edit/triplet_12.jsonl
  data_type: anime
  max_samples: null
  num_workers: 8
  resize_mode: crop # [direct, padding, crop]
  use_score_rescale: false
  resolution:
    width: 512
    height: 512

# LoRA
lora:
  rank: 64
  alpha: 128
  dropout: 0

  target_modules:
    # Attention
    - to_q
    - to_k
    - to_v
    - add_q_proj
    - add_k_proj
    - add_v_proj
    - to_out.0
    - to_add_out

    # Image FFN
    - img_mlp.net.0.proj
    - img_mlp.net.2

    # Text FFN (optional)
    - txt_mlp.net.0.proj
    - txt_mlp.net.2

# Training
training:
  batch_size: 4
  gradient_accumulation_steps: 1
  num_epochs: 100

  learning_rate: 1e-4
  lr_scheduler: cosine
  lr_warmup_steps: 500
  max_grad_norm: 1.0

  mixed_precision: bf16

  # contrast loss
  contrast_loss_weight: 0.05
  contrast_loss_mode: nce
  contrast_loss_symmetric: true
  # id loss
  id_loss_weight: 0

  optimizer:
    use_8bit_adam: false
    beta1: 0.9
    beta2: 0.999
    weight_decay: 0.001
    epsilon: 1e-8
